# This title should be required to appear.
title = "uncanny_rpc_config"

# General properties
[general]
coverimage_url = "default"
update_interval = 1000

# CPU usage display properties
[cpu_monitor]
title = "CPU"
enabled = true
seperator = "-"
percent_roundoff = 2

# Memory(RAM) usage display properties
[memory_monitor]
title = "RAM"
enabled = true
seperator = "-"
current_roundoff = 2
total_roundoff = 2
